version: '3.8'

services:
  football-analysis:
    build: .
    volumes:
      - ./input_videos:/app/input_videos
      - ./output_videos:/app/output_videos
      - ./models:/app/models
      - ./stubs:/app/stubs
    stdin_open: true # docker run -i
    tty: true # docker run -t
